owner: hoanhho
repo: mirei-monitor
baseUrl: /mirei-monitor
sites:
  - name: Soja
    url: https://soja.co
    maxResponseTime: 5000
    check-status-codes:
      - 200
      - 301
      - 302
    headers:
      User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

  - name: POS Mirei
    url: https://pos.mirei.vn
    maxResponseTime: 5000

  - name: Attenir
    url: https://attenir.vn
    maxResponseTime: 5000

  - name: CheckDate
    url: https://checkdate.vn
    maxResponseTime: 5000
    check-status-codes:
      - 200
      - 301
      - 302
    headers:
      User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

  - name: ERP 15 Mirei
    url: https://erp15.mirei.vn/web/login
    maxResponseTime: 5000

status-website:
  name: Soja Status
  introTitle: "Monitoring hệ thống"
  introMessage: "Theo dõi uptime các website"

assignees:
  - hoanhho
