owner: <username-github>
repo: soja-status

sites:
  - name: Soja
    url: https://soja.co
    maxResponseTime: 5000

  - name: POS Mirei
    url: https://pos.mirei.vn
    maxResponseTime: 5000

  - name: Attenir
    url: https://attenir.vn
    maxResponseTime: 5000

  - name: CheckDate
    url: https://checkdate.vn
    maxResponseTime: 5000

  - name: ERP 15 Mirei
    url: https://erp15.mirei.vn/web/login
    maxResponseTime: 5000

status-website:
  name: Soja Status
  introTitle: "Monitoring hệ thống"
  introMessage: "Theo dõi uptime các website"

assignees:
  - <username-github>
